# Generated by Django 3.1.2 on 2020-10-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nama',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='nim',
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
    ]
