# Generated by Django 3.1.2 on 2020-10-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201027_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, null=True)),
                ('kategori', models.CharField(choices=[('Pendidikan', 'Pendidikan'), ('Non-Pendidikan', 'Non-Pendidikan')], max_length=50, null=True)),
                ('penulis', models.CharField(max_length=50, null=True)),
                ('abstrak', models.TextField(max_length=300, null=True)),
                ('berkas', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
