# Generated by Django 3.1.2 on 2020-10-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201027_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='abstrak',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
