# Generated by Django 3.1.2 on 2020-10-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201027_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='penulis',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
