# Generated by Django 3.1.2 on 2020-10-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201027_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='prodi',
        ),
    ]
