# Generated by Django 3.1.2 on 2020-10-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_account_prodi'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='prodi',
            field=models.CharField(choices=[('Pendidikan', 'Pendidikan'), ('Sastra', 'Sastra')], max_length=50, null=True),
        ),
    ]
